export const quotes = [
    '"The world is a book and those who do not travel read only a page." ~ Saint Augustine',
    '"Not all those who wander are lost" ~ J.R.R. Tolkien',
    '"Life is either a daring adventure or nothing at all" ~ Helen Keller',
    '"Take only memories, leave only footprints" ~ Chief Seattle',
    '"Travel is  fatal to prejudice, bigotry, and narrow mindedness, and many of our people need it sorely on these accounts." ~ Mark Twain',
    '" The real voyage of discovery consists not in seeking new landscapes, but in having new eyes." ~ Marcel Proust',
    '"Travel makes one modest, you see what a tiny place you occupy in the world." ~ Gustave Flaubert',
    '"Twenty years from now you will be more disappointed by the things you didn"t do than by the ones you did do" ~ H. Jackson Brown Jr.',
    'Never go on trips with anyone you do not love." ~ Hemmingway',
    '"Like all great travellers, I have seen more than I remember and remember more than I have seen."',
    '"Traveling - it leaves you speechless, then turns you into a storyteller." - Ibn Battuta',
    '"If you think adventure is dangerous, try routine, it"s lethal" ~ Paul Coelho',
    '"Great things never came from comfort zones.',
    '"If you are always trying to be normal, you will never know how amazing you can be." ~ Maya Angelou',
    '"Stop worrying about the potholes in the road and enjoy the journey" ~ Babs Hoffman',
    '"Fear is only temporary. Regrets last forever."',
    '"Life begins at the end of your comfort zone."',
    '"Travel doesn"t become adventure until you leave yourself behind"',
    '"Climb the mountain so you can see the world, not so the world can see you.',
    '"Jobs fill your pocket but adventures fill your soul."',
    '"DON"T WORRY ABOUT THE WORLD ENDING TODAY, IT"S ALREADY TOMORROW IN AUSTRALIA." ~ CHARLES M. SCHULZ',
    '"I HAVE FOUND OUT THAT THERE AIN"T NO SURER WAY TO FIND OUT WHETHER YOU LIKE PEOPLE OR HATE THEM THAN TO TRAVEL WITH THEM." ~ MARK TWAIN',
    '"A JOURNEY IS LIKE MARRIAGE. THE CERTAIN WAY TO BE WRONG IS TO THINK YOU CONTROL IT." ~ JOHN STEINBECK',
    '"DRINK HEAVILY WITH LOCALS WHENEVER POSSIBLE ~ ANTHONY BOURDAIN"',
    '"I TOLD THE DOCTOR I BROKE MY LEG IN TWO PLACES. HE TOLD ME TO QUIT GOING TO THOSE PLACES ~ HENNY YOUNGMAN"',
    'THERE IS NOTHING SAFER THAN FLYING, IT"S CRASHING THAT IS DANGEROUS ~ THEO COWAN',
    '"I ALWAYS LIKE TO GO TO WASHINGTON D.C. IT GIVES ME A CHANCE TO VISIT MY MONEY. ~ BOB HOPE"',
    '"JET LAG IS FOR AMATEURS ~ DICK CLARK"',
    '"TRAVEL IS GLAMOROUS ONLY IN RETROSPECT." ~ PAUL THEROUX',
    '"I WISH I HAD NEVER GONE TRAVELING. SAID NO ONE EVER."',
    '"Man cannot discover new oceans unless he has the courage to lose sight of the shore." ~Andre Gide',
    '"It"s Better to Travel Well than to Arrive" ~ Buddha',
    '"It is not the destination where you end up but the mishaps and memories you create along the way."',
    '"The important thing is to never stop questioning. Curiosity has its own reason for existing" ~ Albert Einstein',
    '"Travel is the only thing you buy that makes you richer."',
    '"I would rather own a little and see the world than own the world and see a little of it." ~ Alexander Sattler',
    ' "It is better to see something once than to hear about it a thousand times."',
    '"The real voyage of discovery consists not in seeking new landscapes, but having new eyes." ~ Marcel Proust',
    '"WHEN WAS THE LAST TIME YOU DID SOMETHING FOR THE FIRST TIME?" ~ ANONYMOUS',
    '"SOMEDAY I"M GOING TO BE FREE AND I"M GOING TO TRAVEL THE WORLD"',
    '"You may say that I"m a dreamer, but I"m not the only one. I hope someday you"ll join us and the world will be as one." ~ ',
    '"Live with no excuses and travel with no regrets" ~ Oscar Wilde',
    '"We travel not to escape life but for life not to escape us."',
    '"People don"t take trips, trips take people."',
    '"Don"t listen to what they say, go see" ~ Chinese Proverb',
    'Don"t Quit Your Day Dream',
    '"I don"t know where I"m going, but I"m on my way"',
    '"Oh, the places you"ll go." ~ Dr. Seuss',
    '"TRY TO BE A RAINBOW IN SOMEONE ELSE"S CLOUD" ~ MAYA ANGELOU',
    'LIFE"S A JOURNEY, NOT A DESTINATION" ~AEROSMITH',
    '"Where to next?"',
    '"TO TRAVEL IS TO LIVE" ~ HANS CHRISTIAN ANDERSON',
    '"I WANT TO MAKE MEMORIES ALL OVER THE WORLD"',
    '"Whenever you find yourself on the side of majority, it"s time to pause and reflect."',
    '"The world is changed by your example, not your opinion." ~ Paul Coelho',
    '"To travel is to discover that everyone is wrong about other countries." ~ Aldous Huxley',
    '"You must be the change you wish to see in the world." ~ Gandhi',
    '"There"s a sunrise and sunset every single day, and they"re absolutely free. Don"t miss so many of them."',
    '"Life isn"t about finding yourself. Life is about creating yourself."',
    '"If your ship doesn"t come in, swim out to it." ~ Johnathan Winters',
    '"Without new experiences, something inside us sleeps. The sleeper must awaken."',
    '"Those who follow the crowd usually get lost in it."',
    '"Doing what you like is freedom, liking what you do is happiness."',
    '"Because when you stop and look around, this life is pretty amazing."',
    '"This heart of mine was made to travel this world"',
    '"The Impulse to Travel is one of the hopeful symptoms of life"',
    '"Let"s find some beautiful place to get lost"',
    '"I"m in love with cities I"ve never been to and people I"ve never met." ~ John Green',
    '"Travel, the best way to be lost and found at the same time." ~Brenna Smith',
    '"The journey is my home."',
    '"It"s a big world out there, it would be a shame not to experience it."',
    '"You can shake the sand from your shoes, but not from your soul."',
    '"STOP BEING AFRAID OF WHAT COULD GO WRONG AND THINK OF WHAT COULD GO RIGHT." ~ ANONYMOUS',
    '"We wander for distraction, but we travel for fulfillment." ~ Hilaire Belloc',
    '"It doesn"t matter where you"re going, it"s who you have beside you.',
    '"Traveling is not something you"re good at. It"s something you do, like breathing." ~ Gayle Foreman',
    '"All we have to decide is what to do with the time that is given us." ~ J.R.R. Tolkien',
    '"It feels good to be lost in the right direction."',
    '"Traveling allows you to become so many different versions of yourself."',
    '"Travel has a way of stretching the mind." ~ Ralph Crawshaw',
    '"Wandering re-establishes the original harmony which once existed between man and the universe." ~ Anotole France',
    '"All journeys have secret destinations of which the traveler is unaware."',
    '"A journey is best measured in friends rather than miles." ~ Tim Cayhill',
    '"Just Go. Go See all the Beauty in the World"',
    '"I travel not to go anywhere but to go. I travel for travel"s sake."',
    '"If you"re twenty-two, physically fit, hungry to learn and be better, I urge you to travel - as far and as widely as possible. Sleep on floors if you have to. Find out how other people live and eat and cook. Learn from them - wherever you go."',
    '"Because In The End, You Won"t Remember The Time You Spent Working In An Office Or Mowing Your Lawn. Climb That Damn Mountain." ~ Jack Kerouak',
    '"Paris is Always a Good Idea ~ Audrey Hepburn"',
    '"You only live once, but if you do it right, once is enough." ~Mae West',
    '"The biggest adventure you can ever take is to live the life of your dreams ~ Oprah Winfrey"',
    '"Perhaps travel cannot prevent bigotry, but by demonstrating that all peoples cry, laugh, eat, worry and die, it can introduce the idea that if we try and understand each other, we may even become friends." ~ Maya Angelou',
    '"Two roads diverged in a wood and I - I took the one less traveled by, and that has made all the difference" ~ Robert Frost',
    '"We travel, initially, to lose ourselves; and we travel next, to find ourselves." ~ Pico Iyer',
    '"Once a year, go someplace you"ve never been before." ~ Dalai Lama',
    '"Though we travel the world over to find the beautiful, we must carry it with us or we find it not. ~ Ralph Waldo Emerson"',
    '"The only people who ever get anyplace interesting are the people who get lost." ~ Henry David Thoreau',
    '"There is no moment of delight in any pilgrimage like the beginning of it" ~ Charles Dudley Warner',
    ' "The most beautiful in the world is, of course, the world itself." - Wallace Stevens',
    '"Keep your face always toward the sunshine - and shadows will fall behind you." ~ Walt Whitman',
    '"Try to be a rainbow in someone else"s cloud" ~ Maya Angelou',
    '"You go away for a long time and return a different person - you never come all the way back"',
];
